### PR TITLE
PR-36: Extra feature unit test 

### PR DESCRIPTION
**Pull request by tungleu**
This PR references Issue #85 

Unit tests have been created for profile feature

### CODE REVIEW

**Review by ys-lin — DISMISSED** [review]
Unit tests approved by Travis

**Review by RGPosadas — APPROVED** [review]
Approved since test works locally and on Travis

**Comment by muhanator** [comment]
Unit tests pass successfully on locally and on Travis

**Comment by muhanator** [comment]
The unit test passes locally and on Travis

**Comment by muhanator** [comment]
The unit test passes locally and on Travis

**Review by muhanator — APPROVED** [review]
The unit test passes locally and it passes on Travis

**Pull request merged**
